# Generated by Django 3.1.5 on 2021-02-19 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contaminant_area', models.CharField(choices=[('', 'Choose Area'), ('Outdoors', 'Outdoors'), ('Kitchen', 'Kitchen'), ('Living Room', 'Living Room'), ('Bedroom', 'Bedroom'), ('Bathroom', 'Bathroom')], max_length=40)),
                ('image', models.ImageField(upload_to='image/data')),
                ('tag', models.CharField(help_text='Add a tag', max_length=50)),
                ('description', models.TextField(help_text='Add a description', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Add a title to dataset', max_length=200)),
                ('contaminant_levels', models.CharField(help_text='Add a contaminant level', max_length=30)),
                ('health_status', models.CharField(help_text='Add health Status', max_length=80)),
            ],
        ),
    ]
